import { Ejercicio } from '../tipos';

/**
 * Ejercicios hermanos (docs/DISENO_PRACTICA_ADAPTATIVA.md §3.2): para cada casilla (tipo × nivel) de una unidad que
 * tenía un solo ejercicio, otro del mismo tipo, nivel y concepto, con otros datos. Se agregan a su unidad por el título
 * (ver `conVariantes` en ../tipos.ts). Como en el resto del curso, todo es pseudocódigo: no hay que programar.
 */
export const variantesPensamiento: Record<string, Ejercicio[]> = {
  'Descomponer, reconocer patrones y abstraer': [
    {
      tipo: 'matching',
      titulo: 'Los pilares en la feria de ciencias',
      enunciado: 'Une cada pilar del pensamiento computacional con el ejemplo que lo muestra, en la organización de la feria de ciencias.',
      dificultad: 'basico',
      parejas: [
        ['Descomponer', 'Separar la feria en stands, horarios, jurados y premios'],
        ['Reconocer patrones', 'Notar que inscribir stands es como inscribir equipos del torneo'],
        ['Abstraer', 'Para asignar el salón importa el tamaño del stand, no su tema'],
        ['Diseñar el algoritmo', 'Escribir los pasos: inscribir, asignar salón, publicar el horario'],
      ],
    },
    {
      tipo: 'drag_drop',
      titulo: 'Abstraer: los refrigerios de la jornada',
      enunciado: '*Problema: calcular cuánto dinero hace falta para los refrigerios de la jornada deportiva.*\n\nAbstrae: clasifica cada dato.',
      dificultad: 'basico',
      categorias: ['Importa para resolverlo', 'Se puede ignorar'],
      elementos: [
        ['Número de estudiantes inscritos', 0],
        ['Número de docentes que acompañan', 0],
        ['Precio de cada refrigerio', 0],
        ['El color del uniforme', 1],
        ['La materia favorita de cada estudiante', 1],
        ['El nombre del colegio vecino', 1],
      ],
      errorComun: [1],
    },
    {
      tipo: 'mcq',
      titulo: 'El patrón de contar',
      enunciado:
        'Contar cuántos estudiantes llegaron tarde, cuántos días llovió en el mes y cuántos goles fueron de penalti. ¿Qué patrón comparten?',
      dificultad: 'basico',
      opciones: [
        'Todos recorren los datos y suman 1 cada vez que se cumple una condición.',
        'Todos usan números decimales.',
        'Todos calculan un promedio.',
        'No tienen nada en común: son temas distintos.',
      ],
      correcta: 0,
      explicacion:
        'Los tres se resuelven con un contador: recorrer los datos y sumar 1 cuando se cumple la condición (llegó tarde, llovió, fue penalti). El mismo algoritmo sirve para los tres.',
      errorComun: 3,
    },
    {
      tipo: 'ordering',
      titulo: 'Los pilares para el horario del laboratorio',
      enunciado: 'Ordena cómo se aplican los pilares para resolver *«repartir las horas del laboratorio de informática entre los grupos»*.',
      dificultad: 'basico',
      pasos: [
        'Descomponer: equipos, grupos, horas y docentes',
        'Reconocer patrones: repartir computadores es como repartir libros de la biblioteca',
        'Abstraer: importa cuántos estudiantes tiene cada grupo, no sus nombres',
        'Diseñar el algoritmo: los pasos para asignar las horas',
      ],
      errorComun: [3, 0, 1, 2],
    },
  ],

  'El robot que sigue órdenes': [
    {
      tipo: 'fill_code',
      titulo: 'Completa: llegar a la bandera',
      enunciado: 'El robot empieza en (0, 0) mirando hacia arriba y la bandera está en **(1, 2)**. Completa el programa para que llegue.',
      dificultad: 'basico',
      lenguaje: 'text',
      plantilla: 'Repetir ___a___ veces:\n    AVANZAR\n___b___\nAVANZAR',
      huecos: { a: '2', b: { regex: 'girar[_ ]?derecha', ejemplo: 'GIRAR_DERECHA' } },
      errorComun: { b: 'GIRAR_IZQUIERDA' },
    },
    {
      tipo: 'drag_drop',
      titulo: '¿El robot entiende esta orden?',
      enunciado: 'El robot solo entiende AVANZAR, GIRAR_DERECHA, GIRAR_IZQUIERDA y Repetir. Clasifica cada orden.',
      dificultad: 'basico',
      categorias: ['El robot la entiende', 'Es ambigua o no la entiende'],
      elementos: [
        ['AVANZAR', 0],
        ['Repetir 3 veces: GIRAR_IZQUIERDA', 0],
        ['Camina hasta la pared', 1],
        ['Gira un poco', 1],
        ['GIRAR_DERECHA', 0],
        ['Esquiva el obstáculo', 1],
      ],
      errorComun: [4],
    },
  ],

  'Leer, calcular y escribir': [
    {
      tipo: 'mcq',
      titulo: 'La flecha guarda el último valor',
      enunciado: '¿Cuánto vale **y** al final?\n\n```\ny <- 10\ny <- y - 4\ny <- y * 2\n```',
      dificultad: 'basico',
      opciones: ['12', '16', '6', 'Nada: y no puede cambiar de valor'],
      correcta: 0,
      explicacion: 'y empieza en 10; y <- y - 4 guarda 6; y <- y * 2 guarda 12. Cada flecha reemplaza el valor anterior.',
      errorComun: 3,
    },
    {
      tipo: 'matching',
      titulo: '¿Cuánto da cada operación?',
      enunciado: 'Une cada operación de pseudocódigo con su resultado. Recuerda que * y / van antes que + y −.',
      dificultad: 'basico',
      parejas: [
        ['20 MOD 6', '2'],
        ['trunc(20 / 6)', '3'],
        ['7 + 3 * 2', '13'],
        ['(7 + 3) * 2', '20'],
        ['10 / 4', '2.5'],
      ],
    },
    {
      tipo: 'fill_code',
      titulo: 'Completa: el promedio de dos notas',
      enunciado: 'Completa el algoritmo para que calcule bien el promedio de dos notas.',
      dificultad: 'basico',
      lenguaje: 'text',
      plantilla: 'Algoritmo Promedio\n    Leer nota1\n    Leer nota2\n    promedio <- (___a___ + nota2) / ___b___\n    Escribir \"Promedio: \", ___c___\nFinAlgoritmo',
      huecos: { a: 'nota1', b: '2', c: 'promedio' },
      errorComun: { b: '1' },
    },
    {
      tipo: 'ordering',
      titulo: 'Ordena: minutos y segundos',
      enunciado: 'Ordena el algoritmo que convierte una cantidad de segundos en minutos y segundos.',
      dificultad: 'basico',
      pasos: [
        'Algoritmo Tiempo',
        'Leer segundos',
        'minutos <- trunc(segundos / 60)',
        'resto <- segundos - minutos * 60',
        'Escribir minutos, " min ", resto, " s"',
        'FinAlgoritmo',
      ],
      errorComun: [0, 1, 3, 2, 4, 5],
    },
  ],

  'Leer un diagrama de flujo': [
    {
      tipo: 'drag_drop',
      titulo: '¿Qué figura va en cada paso?',
      enunciado: 'Ubica cada paso del algoritmo del promedio en la figura del diagrama de flujo que le corresponde.',
      dificultad: 'basico',
      categorias: ['Óvalo (inicio o fin)', 'Paralelogramo (entrada o salida)', 'Rectángulo (proceso)', 'Rombo (decisión)'],
      elementos: [
        ['Inicio', 0],
        ['Leer nota1, nota2', 1],
        ['promedio <- (nota1 + nota2) / 2', 2],
        ['¿promedio >= 3?', 3],
        ['Escribir "Aprobó"', 1],
        ['Fin', 0],
      ],
      errorComun: [4],
    },
    {
      tipo: 'ordering',
      titulo: 'Del diagrama al pseudocódigo: par o impar',
      enunciado: 'Ordena el pseudocódigo que corresponde al diagrama de «¿el número es par?».',
      dificultad: 'basico',
      pasos: ['Algoritmo ParImpar', 'Leer n', 'Si n MOD 2 = 0 Entonces', '    Escribir "Par"', 'SiNo', '    Escribir "Impar"', 'FinSi', 'FinAlgoritmo'],
      errorComun: [0, 1, 2, 5, 4, 3, 6, 7],
    },
  ],

  'Seguir un algoritmo con lápiz y papel': [
    {
      tipo: 'fill_code',
      titulo: 'Completa la tabla: otra prueba',
      enunciado: 'Completa la prueba de escritorio: escribe el valor que queda en cada variable después de cada línea.',
      dificultad: 'intermedio',
      lenguaje: 'text',
      plantilla:
        'Algoritmo            Valor después de la línea\nx <- 3               x = 3\ny <- x + 4           y = ___v1___\nx <- y * x           x = ___v2___\ny <- x - y           y = ___v3___',
      huecos: { v1: '7', v2: '21', v3: '14' },
      errorComun: { v2: '9' },
    },
    {
      tipo: 'ordering',
      titulo: 'La prueba de escritorio, con un ejemplo',
      enunciado: 'Vas a probar un algoritmo que promedia notas. Ordena lo que haces.',
      dificultad: 'basico',
      pasos: [
        'Elegir los datos: n = 3 y las notas 4, 2 y 3',
        'Dibujar una columna para n, i, nota y suma',
        'Seguir el algoritmo línea por línea',
        'Anotar cada valor nuevo en su columna',
        'Comparar el promedio obtenido con 3, el esperado',
      ],
      errorComun: [1, 0, 2, 3, 4],
    },
  ],

  'Si, SiNo y condiciones compuestas': [
    {
      tipo: 'drag_drop',
      titulo: '¿Verdadera o falsa? Otra ronda',
      enunciado: 'Con **nota = 3.5**, **asistio = Falso** y **curso = "B"**, clasifica cada condición.',
      dificultad: 'basico',
      categorias: ['Verdadera', 'Falsa'],
      elementos: [
        ['nota >= 3 Y NO asistio', 0],
        ['nota >= 3 Y asistio', 1],
        ['nota < 3 O asistio', 1],
        ['curso = "A" O curso = "B"', 0],
        ['NO (nota > 4)', 0],
        ['nota > 3.5', 1],
      ],
      errorComun: [5],
    },
    {
      tipo: 'mcq',
      titulo: 'La tabla de verdad de O',
      enunciado: 'Si **A** es Falso y **B** es Falso, ¿cuánto vale **A O B**?',
      dificultad: 'basico',
      opciones: ['Verdadero', 'Falso', 'Depende de B', 'No se puede saber'],
      correcta: 1,
      explicacion: 'Con O basta con que una sea verdadera. Si las dos son falsas, el resultado es Falso.',
      errorComun: 0,
    },
    {
      tipo: 'fill_code',
      titulo: 'Completa: ¿puede entrar a la piscina?',
      enunciado: 'Pueden entrar quienes midan **1.40 m o más** **y** tengan el permiso firmado. Completa la condición.',
      dificultad: 'basico',
      lenguaje: 'text',
      plantilla:
        'Leer estatura, permiso\nSi estatura >= 1.40 ___a___ permiso = "si" Entonces\n    Escribir "Puede entrar"\nSiNo\n    Escribir "No puede entrar"\nFinSi',
      huecos: { a: { regex: 'y|&&', ejemplo: 'Y' } },
      errorComun: { a: 'O' },
    },
    {
      tipo: 'mcq',
      titulo: 'Decisiones anidadas: el descuento',
      enunciado:
        '¿Qué escribe este algoritmo si el total es **50000**?\n\n```\nLeer total\nSi total >= 100000 Entonces\n    Escribir "Descuento del 20 %"\nSiNo\n    Si total >= 50000 Entonces\n        Escribir "Descuento del 10 %"\n    SiNo\n        Escribir "Sin descuento"\n    FinSi\nFinSi\n```',
      dificultad: 'intermedio',
      opciones: ['Descuento del 20 %', 'Descuento del 10 %', 'Sin descuento', 'Los tres mensajes'],
      correcta: 1,
      explicacion: '50000 >= 100000 es falso, así que va al SiNo. Allí 50000 >= 50000 es verdadero (mayor O IGUAL): escribe «Descuento del 10 %».',
      errorComun: 2,
    },
  ],

  'Para, Mientras y Repetir': [
    {
      tipo: 'drag_drop',
      titulo: '¿Para o Mientras? Otra ronda',
      enunciado: 'Clasifica cada situación según la estructura más adecuada.',
      dificultad: 'basico',
      categorias: ['Para (sé cuántas veces)', 'Mientras o Repetir (no sé cuántas veces)'],
      elementos: [
        ['Escribir los números del 1 al 100', 0],
        ['Leer notas hasta que escriban -1', 1],
        ['Sumar lo recaudado en los 12 meses del año', 0],
        ['Esperar hasta que el semáforo cambie a verde', 1],
        ['Repartir 40 hojas, una por estudiante', 0],
        ['Pedir un número hasta que esté entre 1 y 10', 1],
      ],
      errorComun: [3],
    },
    {
      tipo: 'mcq',
      titulo: '¿Cuántas veces con Paso 3?',
      enunciado: '¿Cuántos números escribe?\n\n```\nPara i <- 1 Hasta 10 Con Paso 3 Hacer\n    Escribir i\nFinPara\n```',
      dificultad: 'intermedio',
      opciones: ['3', '4', '10', '5'],
      correcta: 1,
      explicacion: 'i toma 1, 4, 7 y 10: cuatro valores. El 10 se escribe porque «Hasta 10» incluye el límite; el siguiente sería 13 y ya no entra.',
      errorComun: 0,
    },
    {
      tipo: 'fill_code',
      titulo: 'Completa: la cuenta regresiva que termina',
      enunciado: 'Completa el algoritmo para que escriba 5, 4, 3, 2 y 1, y **termine**.',
      dificultad: 'intermedio',
      lenguaje: 'text',
      plantilla: 'contador <- 5\nMientras contador ___a___ 1 Hacer\n    Escribir contador\n    contador <- contador ___b___ 1\nFinMientras',
      huecos: { a: '>=', b: '-' },
      errorComun: { b: '+' },
    },
    {
      tipo: 'ordering',
      titulo: 'Ordena: sumar hasta el cero',
      enunciado: 'Ordena el algoritmo que suma los números que escribe el usuario hasta que escriba 0, y al final muestra la suma.',
      dificultad: 'basico',
      pasos: ['suma <- 0', 'Repetir', '    Leer n', '    suma <- suma + n', 'Hasta Que n = 0', 'Escribir suma'],
      errorComun: [1, 0, 2, 3, 4, 5],
    },
  ],

  'Contadores, acumuladores y banderas': [
    {
      tipo: 'matching',
      titulo: 'Cada variable con su papel',
      enunciado: 'Une cada instrucción con el papel que cumple en el algoritmo.',
      dificultad: 'basico',
      parejas: [
        ['tarde <- tarde + 1', 'Cuenta a los que llegaron tarde'],
        ['total <- total + precio', 'Acumula lo recaudado'],
        ['hayCero <- Verdadero', 'Bandera: recuerda que apareció un cero'],
        ['total <- 0 (antes del ciclo)', 'Inicializa el acumulador'],
        ['Escribir total (después del ciclo)', 'Muestra el resultado del acumulador'],
      ],
    },
    {
      tipo: 'fill_code',
      titulo: 'Completa: los días de lluvia',
      enunciado: 'Completa el algoritmo para que sume los milímetros de lluvia del mes y cuente los días en que llovió.',
      dificultad: 'intermedio',
      lenguaje: 'text',
      plantilla:
        'dias <- 0\nlluvia <- 0\nPara i <- 1 Hasta 30 Hacer\n    Leer mm\n    lluvia <- lluvia + ___a___\n    Si mm > 0 Entonces\n        dias <- dias + ___b___\n    FinSi\nFinPara',
      huecos: { a: 'mm', b: '1' },
      errorComun: { a: '1' },
    },
    {
      tipo: 'mcq',
      titulo: 'El contador que se reinicia',
      enunciado:
        'Las notas son **3.5**, **4.0**, **2.0** y **4.5**, en ese orden. ¿Qué escribe el algoritmo?\n\n```\nPara i <- 1 Hasta 4 Hacer\n    Leer nota\n    aprobados <- 0\n    Si nota >= 3 Entonces\n        aprobados <- aprobados + 1\n    FinSi\nFinPara\nEscribir aprobados\n```',
      dificultad: 'intermedio',
      opciones: ['1', '3', '0', '4'],
      correcta: 0,
      explicacion:
        'aprobados <- 0 está DENTRO del ciclo: en cada vuelta vuelve a cero. En la última vuelta queda en 0 y 4.5 lo sube a 1. El contador debe inicializarse antes del ciclo; así daría 3.',
      errorComun: 1,
    },
    {
      tipo: 'ordering',
      titulo: 'Ordena: ¿alguien llegó tarde?',
      enunciado: 'Ordena el algoritmo que averigua si algún estudiante llegó tarde (minutos de retraso mayores que 0).',
      dificultad: 'intermedio',
      pasos: [
        'hayTarde <- Falso',
        'Para i <- 1 Hasta n Hacer',
        '    Leer minutos',
        '    Si minutos > 0 Entonces',
        '        hayTarde <- Verdadero',
        '    FinSi',
        'FinPara',
        'Escribir hayTarde',
      ],
      errorComun: [1, 0, 2, 3, 4, 5, 6, 7],
    },
  ],

  'Mayor, menor y promedio': [
    {
      tipo: 'mcq',
      titulo: 'El menor que empieza en cero',
      enunciado:
        'Este algoritmo busca el **menor** precio de tres tiendas:\n\n```\nmenor <- 0\nPara i <- 1 Hasta 3 Hacer\n    Leer precio\n    Si precio < menor Entonces\n        menor <- precio\n    FinSi\nFinPara\nEscribir menor\n```\n\nLos precios son **5000**, **8000** y **3000**. ¿Qué escribe?',
      dificultad: 'intermedio',
      opciones: ['3000', '0', '5000', '8000'],
      correcta: 1,
      explicacion:
        'Ningún precio es menor que 0, así que menor nunca cambia: escribe 0, que ni siquiera está en los datos. Se esperaba 3000; la referencia debe empezar con el primer dato.',
      errorComun: 0,
    },
    {
      tipo: 'ordering',
      titulo: 'Ordena: el menor de n datos',
      enunciado: 'Ordena el algoritmo que encuentra el menor de n datos usando el primero como referencia.',
      dificultad: 'intermedio',
      pasos: [
        'Leer n',
        'Leer x',
        'menor <- x',
        'Para i <- 2 Hasta n Hacer',
        '    Leer x',
        '    Si x < menor Entonces',
        '        menor <- x',
        '    FinSi',
        'FinPara',
        'Escribir menor',
      ],
      errorComun: [0, 2, 1, 3, 4, 5, 6, 7, 8, 9],
    },
    {
      tipo: 'fill_code',
      titulo: 'Completa: el mayor',
      enunciado: 'Completa el algoritmo para que encuentre el **mayor** de n datos.',
      dificultad: 'intermedio',
      lenguaje: 'text',
      plantilla: 'Leer x\nmayor <- ___a___\nPara i <- 2 Hasta n Hacer\n    Leer x\n    Si x ___b___ mayor Entonces\n        mayor <- x\n    FinSi\nFinPara',
      huecos: { a: 'x', b: '>' },
      errorComun: { b: '<' },
    },
    {
      tipo: 'drag_drop',
      titulo: '¿Qué patrón necesita? Otra ronda',
      enunciado: 'Clasifica cada tarea según el patrón de algoritmo que necesita.',
      dificultad: 'basico',
      categorias: ['Acumulador (sumar)', 'Contador (contar)', 'Mayor o menor (comparar)'],
      elementos: [
        ['Total de puntos del torneo', 0],
        ['Cuántos estudiantes sacaron 5.0', 1],
        ['El precio más barato de la tienda', 2],
        ['Suma de las horas de monitoría', 0],
        ['Cuántos libros se prestaron hoy', 1],
        ['La nota más alta del parcial', 2],
      ],
      errorComun: [4],
    },
  ],

  'Buscar en una lista': [
    {
      tipo: 'mcq',
      titulo: 'Adivina el número del 1 al 1000',
      enunciado:
        'Tu compañero pensó un número del **1 al 1000** y te dice «mayor» o «menor» después de cada intento. Si siempre dices la mitad del rango que queda, ¿cuántos intentos necesitas **como máximo**?',
      dificultad: 'intermedio',
      opciones: ['10', '100', '500', '1000'],
      correcta: 0,
      explicacion: 'Cada intento descarta la mitad. Con 10 intentos siempre lo encuentras, porque 2¹⁰ = 1024 es mayor que 1000. Por eso la búsqueda binaria es tan rápida.',
      errorComun: 2,
    },
    {
      tipo: 'mcq',
      titulo: 'El mejor caso de la búsqueda lineal',
      enunciado: 'Buscas un nombre en una lista **desordenada** de 50 nombres, revisando uno por uno. En el **mejor caso**, ¿cuántos nombres revisas?',
      dificultad: 'basico',
      opciones: ['1', '25', '50', '10'],
      correcta: 0,
      explicacion: 'El mejor caso es que el nombre sea el primero de la lista: basta con revisar 1. En promedio se revisan unos 25 y en el peor caso los 50.',
      errorComun: 1,
    },
    {
      tipo: 'drag_drop',
      titulo: '¿Lineal o binaria? Otra ronda',
      enunciado: 'Clasifica cada situación según la búsqueda que conviene usar.',
      dificultad: 'intermedio',
      categorias: ['Búsqueda lineal', 'Búsqueda binaria'],
      elementos: [
        ['Buscar una canción en una lista sin orden', 0],
        ['Buscar un teléfono en un directorio ordenado por apellido', 1],
        ['Encontrar una página de un libro sabiendo su número', 1],
        ['Buscar tu cuaderno en un montón de cuadernos', 0],
        ['Buscar una cédula en una lista ordenada de 5000', 1],
        ['Ver si algún día de la semana llovió', 0],
      ],
      errorComun: [2],
    },
    {
      tipo: 'fill_code',
      titulo: 'Completa: ¿en qué posición está?',
      enunciado:
        'Completa la búsqueda lineal que guarda en *posicion* el lugar donde está el buscado (0 si no está), y se **detiene** en cuanto lo encuentra.',
      dificultad: 'avanzado',
      lenguaje: 'text',
      plantilla:
        'posicion <- 0\ni <- 1\nMientras i <= n Y posicion = ___a___ Hacer\n    Si lista[i] = buscado Entonces\n        posicion <- ___b___\n    FinSi\n    i <- i + 1\nFinMientras',
      huecos: { a: '0', b: 'i' },
      errorComun: { b: 'buscado' },
    },
  ],
};
