import { MigrationInterface, QueryRunner } from "typeorm";

export class InitialSchema1779352501667 implements MigrationInterface {
    name = 'InitialSchema1779352501667'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE \`activity_types\` CHANGE \`createdAt\` \`createdAt\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`activity_types\` CHANGE \`updatedAt\` \`updatedAt\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`activity_types\` CHANGE \`deletedAt\` \`deletedAt\` timestamp(6) NULL`);
        await queryRunner.query(`ALTER TABLE \`activity_types\` DROP COLUMN \`configSchema\``);
        await queryRunner.query(`ALTER TABLE \`activity_types\` ADD \`configSchema\` json NULL`);
        await queryRunner.query(`ALTER TABLE \`activities\` CHANGE \`createdAt\` \`createdAt\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`activities\` CHANGE \`updatedAt\` \`updatedAt\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`activities\` CHANGE \`deletedAt\` \`deletedAt\` timestamp(6) NULL`);
        await queryRunner.query(`ALTER TABLE \`activities\` CHANGE \`description\` \`description\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`activities\` CHANGE \`timeLimit\` \`timeLimit\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`activities\` CHANGE \`publishedAt\` \`publishedAt\` timestamp NULL`);
        await queryRunner.query(`ALTER TABLE \`contents\` CHANGE \`createdAt\` \`createdAt\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`contents\` CHANGE \`updatedAt\` \`updatedAt\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`contents\` CHANGE \`deletedAt\` \`deletedAt\` timestamp(6) NULL`);
        await queryRunner.query(`ALTER TABLE \`contents\` CHANGE \`body\` \`body\` longtext NULL`);
        await queryRunner.query(`ALTER TABLE \`contents\` DROP COLUMN \`metadata\``);
        await queryRunner.query(`ALTER TABLE \`contents\` ADD \`metadata\` json NULL`);
        await queryRunner.query(`ALTER TABLE \`learning_units\` DROP FOREIGN KEY \`FK_cb4ada233555d57c4f6e50609ad\``);
        await queryRunner.query(`ALTER TABLE \`learning_units\` CHANGE \`description\` \`description\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`learning_units\` CHANGE \`topicId\` \`topicId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`topics\` CHANGE \`description\` \`description\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`sections\` CHANGE \`description\` \`description\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`classes\` CHANGE \`description\` \`description\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`classes\` CHANGE \`startDate\` \`startDate\` date NULL`);
        await queryRunner.query(`ALTER TABLE \`classes\` CHANGE \`endDate\` \`endDate\` date NULL`);
        await queryRunner.query(`ALTER TABLE \`classes\` CHANGE \`maxStudents\` \`maxStudents\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`enrollments\` CHANGE \`left_at\` \`left_at\` timestamp NULL`);
        await queryRunner.query(`ALTER TABLE \`enrollments\` CHANGE \`last_activity_at\` \`last_activity_at\` timestamp NULL`);
        await queryRunner.query(`ALTER TABLE \`user_affiliations\` CHANGE \`currentSemester\` \`currentSemester\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`tutor_conversations\` CHANGE \`createdAt\` \`createdAt\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`tutor_conversations\` CHANGE \`updatedAt\` \`updatedAt\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`tutor_conversations\` CHANGE \`deletedAt\` \`deletedAt\` timestamp(6) NULL`);
        await queryRunner.query(`ALTER TABLE \`tutor_conversations\` DROP COLUMN \`metadata\``);
        await queryRunner.query(`ALTER TABLE \`tutor_conversations\` ADD \`metadata\` json NULL`);
        await queryRunner.query(`ALTER TABLE \`activity_questions\` CHANGE \`createdAt\` \`createdAt\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`activity_questions\` CHANGE \`updatedAt\` \`updatedAt\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`activity_questions\` CHANGE \`deletedAt\` \`deletedAt\` timestamp(6) NULL`);
        await queryRunner.query(`ALTER TABLE \`submission_answers\` CHANGE \`isCorrect\` \`isCorrect\` tinyint NULL`);
        await queryRunner.query(`ALTER TABLE \`submission_answers\` CHANGE \`feedback\` \`feedback\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`submissions\` CHANGE \`feedback\` \`feedback\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`submissions\` CHANGE \`startedAt\` \`startedAt\` timestamp NULL`);
        await queryRunner.query(`ALTER TABLE \`submissions\` CHANGE \`submittedAt\` \`submittedAt\` timestamp NULL`);
        await queryRunner.query(`ALTER TABLE \`submissions\` CHANGE \`lastSavedAt\` \`lastSavedAt\` timestamp NULL`);
        await queryRunner.query(`ALTER TABLE \`submissions\` DROP COLUMN \`autosaveData\``);
        await queryRunner.query(`ALTER TABLE \`submissions\` ADD \`autosaveData\` json NULL`);
        await queryRunner.query(`ALTER TABLE \`submissions\` CHANGE \`createdAt\` \`createdAt\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`submissions\` CHANGE \`updatedAt\` \`updatedAt\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`submissions\` CHANGE \`deletedAt\` \`deletedAt\` timestamp(6) NULL`);
        await queryRunner.query(`ALTER TABLE \`review_schedules\` CHANGE \`createdAt\` \`createdAt\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`review_schedules\` CHANGE \`updatedAt\` \`updatedAt\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`review_schedules\` CHANGE \`deletedAt\` \`deletedAt\` timestamp(6) NULL`);
        await queryRunner.query(`ALTER TABLE \`review_schedules\` CHANGE \`lastReviewedAt\` \`lastReviewedAt\` timestamp NULL`);
        await queryRunner.query(`ALTER TABLE \`bank_questions\` CHANGE \`createdAt\` \`createdAt\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`bank_questions\` CHANGE \`updatedAt\` \`updatedAt\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`bank_questions\` CHANGE \`deletedAt\` \`deletedAt\` timestamp(6) NULL`);
        await queryRunner.query(`ALTER TABLE \`bank_questions\` CHANGE \`tags\` \`tags\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`question_banks\` CHANGE \`createdAt\` \`createdAt\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`question_banks\` CHANGE \`updatedAt\` \`updatedAt\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`question_banks\` CHANGE \`deletedAt\` \`deletedAt\` timestamp(6) NULL`);
        await queryRunner.query(`ALTER TABLE \`question_banks\` CHANGE \`description\` \`description\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`prerequisites\` CHANGE \`createdAt\` \`createdAt\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`prerequisites\` CHANGE \`updatedAt\` \`updatedAt\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`prerequisites\` CHANGE \`deletedAt\` \`deletedAt\` timestamp(6) NULL`);
        await queryRunner.query(`ALTER TABLE \`learning_progress\` DROP FOREIGN KEY \`FK_c4ba35959dbdc57dde97ceb7473\``);
        await queryRunner.query(`ALTER TABLE \`learning_progress\` CHANGE \`createdAt\` \`createdAt\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`learning_progress\` CHANGE \`updatedAt\` \`updatedAt\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`learning_progress\` CHANGE \`deletedAt\` \`deletedAt\` timestamp(6) NULL`);
        await queryRunner.query(`ALTER TABLE \`learning_progress\` CHANGE \`lastActivityId\` \`lastActivityId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`execution_results\` CHANGE \`stdout\` \`stdout\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`execution_results\` CHANGE \`stderr\` \`stderr\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`execution_results\` CHANGE \`testCaseLabel\` \`testCaseLabel\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`execution_results\` CHANGE \`createdAt\` \`createdAt\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`execution_results\` CHANGE \`updatedAt\` \`updatedAt\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`execution_results\` CHANGE \`deletedAt\` \`deletedAt\` timestamp(6) NULL`);
        await queryRunner.query(`ALTER TABLE \`achievements\` DROP FOREIGN KEY \`FK_d090264a2b478a21cc8f52552b9\``);
        await queryRunner.query(`ALTER TABLE \`achievements\` CHANGE \`createdAt\` \`createdAt\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`achievements\` CHANGE \`updatedAt\` \`updatedAt\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`achievements\` CHANGE \`deletedAt\` \`deletedAt\` timestamp(6) NULL`);
        await queryRunner.query(`ALTER TABLE \`achievements\` CHANGE \`description\` \`description\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`achievements\` CHANGE \`unlockedById\` \`unlockedById\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`activity_logs\` DROP COLUMN \`metadata\``);
        await queryRunner.query(`ALTER TABLE \`activity_logs\` ADD \`metadata\` json NULL`);
        await queryRunner.query(`ALTER TABLE \`learning_units\` ADD CONSTRAINT \`FK_cb4ada233555d57c4f6e50609ad\` FOREIGN KEY (\`topicId\`) REFERENCES \`topics\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`learning_progress\` ADD CONSTRAINT \`FK_c4ba35959dbdc57dde97ceb7473\` FOREIGN KEY (\`lastActivityId\`) REFERENCES \`activities\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`achievements\` ADD CONSTRAINT \`FK_d090264a2b478a21cc8f52552b9\` FOREIGN KEY (\`unlockedById\`) REFERENCES \`users\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE \`achievements\` DROP FOREIGN KEY \`FK_d090264a2b478a21cc8f52552b9\``);
        await queryRunner.query(`ALTER TABLE \`learning_progress\` DROP FOREIGN KEY \`FK_c4ba35959dbdc57dde97ceb7473\``);
        await queryRunner.query(`ALTER TABLE \`learning_units\` DROP FOREIGN KEY \`FK_cb4ada233555d57c4f6e50609ad\``);
        await queryRunner.query(`ALTER TABLE \`activity_logs\` DROP COLUMN \`metadata\``);
        await queryRunner.query(`ALTER TABLE \`activity_logs\` ADD \`metadata\` longtext COLLATE "utf8mb4_bin" NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`achievements\` CHANGE \`unlockedById\` \`unlockedById\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`achievements\` CHANGE \`description\` \`description\` text NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`achievements\` CHANGE \`deletedAt\` \`deletedAt\` timestamp(6) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`achievements\` CHANGE \`updatedAt\` \`updatedAt\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`achievements\` CHANGE \`createdAt\` \`createdAt\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`achievements\` ADD CONSTRAINT \`FK_d090264a2b478a21cc8f52552b9\` FOREIGN KEY (\`unlockedById\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`execution_results\` CHANGE \`deletedAt\` \`deletedAt\` timestamp(6) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`execution_results\` CHANGE \`updatedAt\` \`updatedAt\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`execution_results\` CHANGE \`createdAt\` \`createdAt\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`execution_results\` CHANGE \`testCaseLabel\` \`testCaseLabel\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`execution_results\` CHANGE \`stderr\` \`stderr\` text NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`execution_results\` CHANGE \`stdout\` \`stdout\` text NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`learning_progress\` CHANGE \`lastActivityId\` \`lastActivityId\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`learning_progress\` CHANGE \`deletedAt\` \`deletedAt\` timestamp(6) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`learning_progress\` CHANGE \`updatedAt\` \`updatedAt\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`learning_progress\` CHANGE \`createdAt\` \`createdAt\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`learning_progress\` ADD CONSTRAINT \`FK_c4ba35959dbdc57dde97ceb7473\` FOREIGN KEY (\`lastActivityId\`) REFERENCES \`activities\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`prerequisites\` CHANGE \`deletedAt\` \`deletedAt\` timestamp(6) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`prerequisites\` CHANGE \`updatedAt\` \`updatedAt\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`prerequisites\` CHANGE \`createdAt\` \`createdAt\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`question_banks\` CHANGE \`description\` \`description\` text NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`question_banks\` CHANGE \`deletedAt\` \`deletedAt\` timestamp(6) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`question_banks\` CHANGE \`updatedAt\` \`updatedAt\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`question_banks\` CHANGE \`createdAt\` \`createdAt\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`bank_questions\` CHANGE \`tags\` \`tags\` text NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`bank_questions\` CHANGE \`deletedAt\` \`deletedAt\` timestamp(6) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`bank_questions\` CHANGE \`updatedAt\` \`updatedAt\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`bank_questions\` CHANGE \`createdAt\` \`createdAt\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`review_schedules\` CHANGE \`lastReviewedAt\` \`lastReviewedAt\` timestamp NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`review_schedules\` CHANGE \`deletedAt\` \`deletedAt\` timestamp(6) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`review_schedules\` CHANGE \`updatedAt\` \`updatedAt\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`review_schedules\` CHANGE \`createdAt\` \`createdAt\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`submissions\` CHANGE \`deletedAt\` \`deletedAt\` timestamp(6) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`submissions\` CHANGE \`updatedAt\` \`updatedAt\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`submissions\` CHANGE \`createdAt\` \`createdAt\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`submissions\` DROP COLUMN \`autosaveData\``);
        await queryRunner.query(`ALTER TABLE \`submissions\` ADD \`autosaveData\` longtext COLLATE "utf8mb4_bin" NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`submissions\` CHANGE \`lastSavedAt\` \`lastSavedAt\` timestamp NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`submissions\` CHANGE \`submittedAt\` \`submittedAt\` timestamp NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`submissions\` CHANGE \`startedAt\` \`startedAt\` timestamp NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`submissions\` CHANGE \`feedback\` \`feedback\` text NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`submission_answers\` CHANGE \`feedback\` \`feedback\` text NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`submission_answers\` CHANGE \`isCorrect\` \`isCorrect\` tinyint NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`activity_questions\` CHANGE \`deletedAt\` \`deletedAt\` timestamp(6) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`activity_questions\` CHANGE \`updatedAt\` \`updatedAt\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`activity_questions\` CHANGE \`createdAt\` \`createdAt\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`tutor_conversations\` DROP COLUMN \`metadata\``);
        await queryRunner.query(`ALTER TABLE \`tutor_conversations\` ADD \`metadata\` longtext COLLATE "utf8mb4_bin" NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`tutor_conversations\` CHANGE \`deletedAt\` \`deletedAt\` timestamp(6) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`tutor_conversations\` CHANGE \`updatedAt\` \`updatedAt\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`tutor_conversations\` CHANGE \`createdAt\` \`createdAt\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`user_affiliations\` CHANGE \`currentSemester\` \`currentSemester\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`enrollments\` CHANGE \`last_activity_at\` \`last_activity_at\` timestamp NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`enrollments\` CHANGE \`left_at\` \`left_at\` timestamp NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`classes\` CHANGE \`maxStudents\` \`maxStudents\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`classes\` CHANGE \`endDate\` \`endDate\` date NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`classes\` CHANGE \`startDate\` \`startDate\` date NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`classes\` CHANGE \`description\` \`description\` text NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`sections\` CHANGE \`description\` \`description\` text NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`topics\` CHANGE \`description\` \`description\` text NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`learning_units\` CHANGE \`topicId\` \`topicId\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`learning_units\` CHANGE \`description\` \`description\` text NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`learning_units\` ADD CONSTRAINT \`FK_cb4ada233555d57c4f6e50609ad\` FOREIGN KEY (\`topicId\`) REFERENCES \`topics\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`contents\` DROP COLUMN \`metadata\``);
        await queryRunner.query(`ALTER TABLE \`contents\` ADD \`metadata\` longtext COLLATE "utf8mb4_bin" NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`contents\` CHANGE \`body\` \`body\` longtext NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`contents\` CHANGE \`deletedAt\` \`deletedAt\` timestamp(6) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`contents\` CHANGE \`updatedAt\` \`updatedAt\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`contents\` CHANGE \`createdAt\` \`createdAt\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`activities\` CHANGE \`publishedAt\` \`publishedAt\` timestamp NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`activities\` CHANGE \`timeLimit\` \`timeLimit\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`activities\` CHANGE \`description\` \`description\` text NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`activities\` CHANGE \`deletedAt\` \`deletedAt\` timestamp(6) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`activities\` CHANGE \`updatedAt\` \`updatedAt\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`activities\` CHANGE \`createdAt\` \`createdAt\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`activity_types\` DROP COLUMN \`configSchema\``);
        await queryRunner.query(`ALTER TABLE \`activity_types\` ADD \`configSchema\` longtext COLLATE "utf8mb4_bin" NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`activity_types\` CHANGE \`deletedAt\` \`deletedAt\` timestamp(6) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`activity_types\` CHANGE \`updatedAt\` \`updatedAt\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`activity_types\` CHANGE \`createdAt\` \`createdAt\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
    }

}
